(jde-project-file-version "1.0")
(jde-set-variables
 '(jde-project-name "ACE2004-Task")
 '(jde-javadoc-gen-destination-directory "./doc/api")
 '(jde-global-classpath (quote ("./build/classes" "../../build/classes" "../../lib")))
 '(jde-run-working-directory ".")
 '(jde-javadoc-display-doc nil)
 '(jde-javadoc-gen-doc-title "Callisto API Specification")
 '(jde-javadoc-gen-header "<b>The Callisto Annotation Tool </b>")
 '(jde-debugger (quote ("JDEbug")))
 '(jde-compile-option-sourcepath (quote ("./src")))
 '(jde-compile-option-directory "./build/classes")
 '(jde-sourcepath (quote ("." "./../../../../atlas/jatlas/src" "./../../../../atlas/jatlas/src" "C:/java/j2sdk/src")))
 '(jde-javadoc-gen-packages (quote ("org.mitre.ace2004")))
 '(jde-run-application-class "org.mitre.jawb.Jawb"))
